services:
  app:
    build:
      context: .
      args:
        - DEV=true
    container_name: club-app
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py init_superuser &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_ENV=dev
      - DB_HOST=osc-dev-db
      - DB_NAME=devdatabase
      - DB_USER=devuser
      - DB_PASS=devpass
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASS=${DJANGO_SUPERUSER_PASS:-changeme}
      - DJANGO_BASE_URL=${DJANGO_BASE_URL:-http://localhost:8000}
      - S3_STORAGE_BACKEND=0
      - CREATE_SUPERUSER=1
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-""}
      - EMAIL_HOST_PASS=${EMAIL_HOST_PASS:-""}
      - CONSOLE_EMAIL_BACKEND=${CONSOLE_EMAIL_BACKEND:-1}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-""}

      - CSRF_TRUSTED_ORIGINS=http://localhost:8000
      - CSRF_COOKIE_SECURE=0
      - SESSION_COOKIE_SECURE=0
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: osc-dev-db
    volumes:
      - postgres-osc-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdatabase
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass

  coverage:
    image: nginx
    ports:
      - '8001:80'
    volumes:
      - ./app/htmlcov:/usr/share/nginx/html

volumes:
  postgres-osc-dev:
